export const T = {
  bg: '#fafaf7',
  surface: '#fff',
  surfaceAlt: '#f4f2ec',
  ink: '#1a1a1a',
  ink2: '#3d3a35',
  ink3: '#6b6760',
  faint: '#a8a49d',
  border: '#e6e2d8',
  borderStrong: '#d4cfc2',
  accent: '#d97757',
  accentBg: '#fff4ec',
  ai: '#7a4cc8',
  aiBg: '#f6f0ff',
  aiBorder: '#dccdf3',
  ok: '#2e7d3e',
  okBg: '#eaf5ec',
  okBorder: '#c8e0cc',
  warn: '#c89a3a',
  warnBg: '#fbf3df',
  warnBorder: '#e8d8a8',
  danger: '#b8413b',
  dangerBg: '#fbe8e4',
  dangerBorder: '#e8c5c0',
  font: '"Inter", system-ui, -apple-system, sans-serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
  radius: { card: 8, button: 6, input: 6, tag: 10 },
} as const
