export const T = {
  bg: 'var(--color-bg)',
  surface: 'var(--color-surface)',
  surfaceAlt: 'var(--color-surface-alt)',
  surfaceHover: 'var(--color-surface-hover)',
  ink: 'var(--color-ink)',
  ink2: 'var(--color-ink-2)',
  ink3: 'var(--color-ink-3)',
  inkInverse: 'var(--color-ink-inverse)',
  faint: 'var(--color-faint)',
  border: 'var(--color-border)',
  borderStrong: 'var(--color-border-strong)',
  accent: 'var(--color-accent)',
  accentHover: 'var(--color-accent-hover)',
  accentBg: 'var(--color-accent-bg)',
  ai: 'var(--color-ai)',
  aiBg: 'var(--color-ai-bg)',
  aiBorder: 'var(--color-ai-border)',
  ok: 'var(--color-ok)',
  okBg: 'var(--color-ok-bg)',
  okBorder: 'var(--color-ok-border)',
  warn: 'var(--color-warn)',
  warnBg: 'var(--color-warn-bg)',
  warnBorder: 'var(--color-warn-border)',
  danger: 'var(--color-danger)',
  dangerBg: 'var(--color-danger-bg)',
  dangerBorder: 'var(--color-danger-border)',
  shadow: 'var(--shadow-elevated)',
  overlay: 'var(--color-overlay)',
  font: '"Inter", system-ui, -apple-system, sans-serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
  radius: { card: 8, button: 6, input: 6, tag: 10 },
} as const
